---
- name: create runit user directory
  file:
    path: /etc/sv/runsvdir-user/
    state: directory
  become: yes

- name: per user services
  template:
    src: run.j2
    dest: /etc/sv/runsvdir-user/run
    mode: 0755
  notify: enable runit-user
  become: yes
        
