;;; hcel-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from hcel.el

(register-definition-prefixes "hcel" '("hcel-"))


;;; Generated autoloads from hcel-client.el

(register-definition-prefixes "hcel-client" '("hcel-"))


;;; Generated autoloads from hcel-haddorg.el

(register-definition-prefixes "hcel-haddorg" '("hcel-"))


;;; Generated autoloads from hcel-minor.el

(register-definition-prefixes "hcel-minor" '("hcel-minor-"))


;;; Generated autoloads from hcel-outline.el

(register-definition-prefixes "hcel-outline" '("hcel"))


;;; Generated autoloads from hcel-results.el

(register-definition-prefixes "hcel-results" '("hcel-"))


;;; Generated autoloads from hcel-source.el

(register-definition-prefixes "hcel-source" '("hcel-"))


;;; Generated autoloads from hcel-utils.el

(register-definition-prefixes "hcel-utils" '("hcel-"))

;;; End of scraped data

(provide 'hcel-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; hcel-autoloads.el ends here
