- name: Install needed packages
  community.general.xbps: 
    name: '{{ item }}'
  loop:
    - stow
    - zsh
    - curl
    - antibody
    - direnv
    - fzf
    - grc
    - tree
    - tmux
- name: Build directories list
  find: 
    paths: [dotfiles/]
    recurse: no
    file_type: directory
  register: files

- name: Deploy dotfiles
  become_user: '{{user}}'
  become: yes
  with_items: '{{files.files}}'
  shell: |
    STOW_PATH={{item.path | replace("dotfiles/", "")}}
    OVERRIDE=$(cat ${STOW_PATH}/.override 2>/dev/null)
    VOID_HOME=$(getent passwd void | cut -d: -f6)
    stow -v --ignore "\.override" -t ${OVERRIDE:-$VOID_HOME} ${STOW_PATH}
  args:
    chdir: ./dotfiles
    executable: /bin/bash

- name: Create empty ~/.profile for user 
  file:
    path: /home/void/.profile
    state: touch
    owner: void
    group: void
    
